import type { Metadata } from "next";
import "./globals.css";
import {Outfit} from 'next/font/google'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({
    subsets:['latin'],
    variable: "--font-outfit"
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-300 flex w-screen h-screen items-center justify-center">
        {children}
      </body>
    </html>
  );
}
